=== ProphetofAtnu/CMakeFileAPISchema/schema/codemodel-v2-target.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "title": "CodeModel v2 Target File",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "name",
    "id",
    "type",
    "backtrace",
    "paths",
    "sources"
  ],
  "properties": {
    "name": {
      "type": "string"
    },
    "id": {
      "type": "string"
    },
    "type": {
      "type": "string",
      "enum": [
        "EXECUTABLE",
        "STATIC_LIBRARY",
        "SHARED_LIBRARY",
        "MODULE_LIBRARY",
        "OBJECT_LIBRARY",
        "INTERFACE_LIBRARY",
        "UTILITY"
      ]
    },
    "backtrace": {
      "type": "integer"
    },
    "folder": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "name"
      ],
      "properties": {
        "name": {
          "type": "string"
        }
      }
    },
    "paths": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "source",
        "build"
      ],
      "properties": {
        "source": {
          "type": "string"
        },
        "build": {
          "type": "string"
        }
      }
    },
    "nameOnDisk": {
      "type": "string"
    },
    "artifacts": {
      "type": "array",
      "items": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "path"
        ],
        "properties": {
          "path": {
            "type": "string"
          }
        }
      }
    },
    "isGeneratorProvided": {
      "type": "boolean"
    },
    "install": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "prefix",
        "destinations"
      ],
      "properties": {
        "prefix": {
          "type": "object",
          "additionalProperties": false,
          "required": [
            "path"
          ],
          "properties": {
            "path": {
              "type": "string"
            }
          }
        },
        "destinations": {
          "type": "array",
          "items": {
            "type": "object",
            "additionalProperties": false,
            "required": [
              "path"
            ],
            "properties": {
              "path": {
                "type": "string"
              },
              "backtrace": {
                "type": "integer"
              }
            }
          }
        }
      }
    },
    "link": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "language"
      ],
      "properties": {
        "language": {
          "type": "string"
        },
        "commandFragments": {
          "type": "array",
          "items": {
            "type": "object",
            "additionalProperties": false,
            "required": [
              "fragment",
              "role"
            ],
            "properties": {
              "fragment": {
                "type": "string"
              },
              "role": {
                "type": "string",
                "enum": [
                  "flags",
                  "libraries",
                  "libraryPath",
                  "frameworkPath"
                ]
              },
              "backtrace": {
                "type": "integer"
              }
            }
          }
        },
        "lto": {
          "type": "boolean"
        },
        "sysroot": {
          "type": "object",
          "required": [
            "path"
          ],
          "properties": {
            "path": {
              "type": "string"
            }
          }
        }
      }
    },
    "archive": {
      "type": "object",
      "properties": {
        "commandFragments": {
          "type": "object",
          "required": [
            "fragment",
            "role"
          ],
          "properties": {
            "fragment": {
              "type": "string"
            },
            "role": {
              "type": "string",
              "enum": [
                "flags",
                "libraries",
                "libraryPath",
                "frameworkPath"
              ]
            }
          }
        },
        "lto": {
          "type": "boolean"
        }
      }
    },
    "dependencies": {
      "type": "array",
      "items": {
        "$id": "dependency",
        "type": "object",
        "required": [
          "id"
        ],
        "properties": {
          "id": {
            "type": "string"
          },
          "backtrace": {
            "type": "integer"
          }
        }
      }
    },
    "fileSets": {
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "name",
          "type",
          "visibility",
          "baseDirectories"
        ],
        "properties": {
          "name": {
            "type": "string"
          },
          "type": {
            "type": "string"
          },
          "visibility": {
            "type": "string",
            "enum": [
              "PUBLIC",
              "PRIVATE",
              "INTERFACE"
            ]
          },
          "baseDirectories": {
            "type": "array",
            "items": {
              "type": "string"
            }
          }
        }
      }
    },
    "sources": {
      "type": "array",
      "items": {
        "$id": "source",
        "type": "object",
        "required": [
          "path"
        ],
        "properties": {
          "path": {
            "type": "string"
          },
          "compileGroupIndex": {
            "type": "integer"
          },
          "sourceGroupIndex": {
            "type": "integer"
          },
          "isGenerated": {
            "type": "boolean"
          },
          "fileSetIndex": {
            "type": "integer"
          },
          "backtrace": {
            "type": "integer"
          }
        }
      }
    },
    "sourceGroups": {
      "type": "array",
      "items": {
        "$id": "sourceGroup",
        "type": "object",
        "required": [
          "name",
          "sourceIndexes"
        ],
        "properties": {
          "name": {
            "type": "string"
          },
          "sourceIndexes": {
            "type": "array",
            "items": {
              "type": "integer"
            }
          }
        }
      }
    },
    "compileGroups": {
      "type": "array",
      "items": {
        "$id": "sourceGroup",
        "type": "object",
        "required": [
          "sourceIndexes",
          "language"
        ],
        "properties": {
          "sourceIndexes": {
            "type": "array",
            "items": {
              "type": "integer"
            }
          },
          "language": {
            "type": "string"
          },
          "languageStandard": {
            "type": "object",
            "required": [
              "standard"
            ],
            "properties": {
              "backtraces": {
                "type": "array",
                "items": {
                  "type": "integer"
                }
              },
              "standard": {
                "type": "string"
              }
            }
          },
          "compileCommandFragments": {
            "type": "array",
            "items": {
              "type": "object",
              "required": [
                "fragment"
              ],
              "properties": {
                "fragment": {
                  "type": "string"
                }
              }
            }
          },
          "includes": {
            "type": "array",
            "items": {
              "type": "object",
              "required": [
                "path"
              ],
              "properties": {
                "path": {
                  "type": "string"
                },
                "isSystem": {
                  "type": "boolean"
                },
                "backtrace": {
                  "type": "integer"
                }
              }
            }
          },
          "frameworks": {
            "type": "array",
            "items": {
              "type": "object",
              "required": [
                "items"
              ],
              "properties": {
                "path": {
                  "type": "string"
                },
                "isSystem": {
                  "type": "boolean"
                },
                "backtrace": {
                  "type": "integer"
                }
              }
            }
          },
          "precompileHeaders": {
            "type": "array",
            "items": {
              "type": "object",
              "required": [
                "header"
              ],
              "properties": {
                "header": {
                  "type": "string"
                },
                "backtrace": {
                  "type": "integer"
                }
              }
            }
          },
          "defines": {
            "type": "array",
            "items": {
              "$id": "define",
              "type": "object",
              "required": [
                "define"
              ],
              "properties": {
                "define": {
                  "type": "string"
                },
                "backtrace": {
                  "type": "integer"
                }
              }
            }
          },
          "sysroot": {
            "type": "object",
            "required": [
              "path"
            ],
            "properties": {
              "path": {
                "type": "string"
              }
            }
          }
        }
      }
    },
    "backtraceGraph": {
      "$ref": "./codemodel-v2-backtrace-graph.json"
    }
  }
}

=== ProphetofAtnu/CMakeFileAPISchema/tests/target-LLVMTestingAnnotations-Debug-3c39d5452e6fcf96404c.json
{
	"archive" : {},
	"artifacts" : 
	[
		{
			"path" : "lib/libLLVMTestingAnnotations.a"
		}
	],
	"backtrace" : 3,
	"backtraceGraph" : 
	{
		"commands" : 
		[
			"add_library",
			"llvm_add_library",
			"add_llvm_library",
			"target_link_libraries",
			"set_property",
			"llvm_update_compile_flags",
			"add_compile_definitions",
			"include",
			"include_directories"
		],
		"files" : 
		[
			"cmake/modules/AddLLVM.cmake",
			"lib/Testing/Annotations/CMakeLists.txt",
			"cmake/modules/HandleLLVMOptions.cmake",
			"CMakeLists.txt"
		],
		"nodes" : 
		[
			{
				"file" : 1
			},
			{
				"command" : 2,
				"file" : 1,
				"line" : 8,
				"parent" : 0
			},
			{
				"command" : 1,
				"file" : 0,
				"line" : 852,
				"parent" : 1
			},
			{
				"command" : 0,
				"file" : 0,
				"line" : 590,
				"parent" : 2
			},
			{
				"command" : 3,
				"file" : 0,
				"line" : 714,
				"parent" : 2
			},
			{
				"command" : 5,
				"file" : 0,
				"line" : 614,
				"parent" : 2
			},
			{
				"command" : 4,
				"file" : 0,
				"line" : 83,
				"parent" : 5
			},
			{
				"file" : 3
			},
			{
				"command" : 7,
				"file" : 3,
				"line" : 926,
				"parent" : 7
			},
			{
				"file" : 2,
				"parent" : 8
			},
			{
				"command" : 6,
				"file" : 2,
				"line" : 92,
				"parent" : 9
			},
			{
				"command" : 6,
				"file" : 2,
				"line" : 113,
				"parent" : 9
			},
			{
				"command" : 6,
				"file" : 2,
				"line" : 1053,
				"parent" : 9
			},
			{
				"command" : 6,
				"file" : 2,
				"line" : 1054,
				"parent" : 9
			},
			{
				"command" : 6,
				"file" : 2,
				"line" : 1055,
				"parent" : 9
			},
			{
				"command" : 8,
				"file" : 3,
				"line" : 1133,
				"parent" : 7
			}
		]
	},
	"compileGroups" : 
	[
		{
			"compileCommandFragments" : 
			[
				{
					"fragment" : " -fPIC -fvisibility-inlines-hidden -Werror=date-time -Werror=unguarded-availability-new -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -pedantic -Wno-long-long -Wc++98-compat-extra-semi -Wimplicit-fallthrough -Wcovered-switch-default -Wno-noexcept-type -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -Wsuggest-override -Wstring-conversion -Wmisleading-indentation -Wctad-maybe-unsupported -g -std=c++17 -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk"
				},
				{
					"fragment" : " -fno-exceptions -funwind-tables -fno-rtti"
				}
			],
			"defines" : 
			[
				{
					"backtrace" : 6,
					"define" : "GTEST_HAS_RTTI=0"
				},
				{
					"backtrace" : 10,
					"define" : "_DEBUG"
				},
				{
					"backtrace" : 11,
					"define" : "_GLIBCXX_ASSERTIONS"
				},
				{
					"backtrace" : 12,
					"define" : "__STDC_CONSTANT_MACROS"
				},
				{
					"backtrace" : 13,
					"define" : "__STDC_FORMAT_MACROS"
				},
				{
					"backtrace" : 14,
					"define" : "__STDC_LIMIT_MACROS"
				}
			],
			"includes" : 
			[
				{
					"path" : "/Users/jacsc/Code/install/llvm-build/lib/Testing/Annotations"
				},
				{
					"path" : "/Users/jacsc/Code/install/llvm-project/llvm/lib/Testing/Annotations"
				},
				{
					"backtrace" : 15,
					"path" : "/Users/jacsc/Code/install/llvm-build/include"
				},
				{
					"backtrace" : 15,
					"path" : "/Users/jacsc/Code/install/llvm-project/llvm/include"
				},
				{
					"backtrace" : 4,
					"isSystem" : true,
					"path" : "/opt/homebrew/include"
				}
			],
			"language" : "CXX",
			"languageStandard" : 
			{
				"backtraces" : 
				[
					3
				],
				"standard" : "17"
			},
			"sourceIndexes" : 
			[
				0
			]
		}
	],
	"dependencies" : 
	[
		{
			"backtrace" : 4,
			"id" : "LLVMDemangle::@3c7ef39cff93a35ba752"
		},
		{
			"backtrace" : 4,
			"id" : "LLVMSupport::@928d1708d80fe1f55e59"
		}
	],
	"folder" : 
	{
		"name" : "Libraries"
	},
	"id" : "LLVMTestingAnnotations::@8267d7babca240e876cd",
	"name" : "LLVMTestingAnnotations",
	"nameOnDisk" : "libLLVMTestingAnnotations.a",
	"paths" : 
	{
		"build" : "lib/Testing/Annotations",
		"source" : "lib/Testing/Annotations"
	},
	"sourceGroups" : 
	[
		{
			"name" : "Source Files",
			"sourceIndexes" : 
			[
				0
			]
		},
		{
			"name" : "Header Files",
			"sourceIndexes" : 
			[
				1,
				2
			]
		}
	],
	"sources" : 
	[
		{
			"backtrace" : 3,
			"compileGroupIndex" : 0,
			"path" : "lib/Testing/Annotations/Annotations.cpp",
			"sourceGroupIndex" : 0
		},
		{
			"backtrace" : 3,
			"path" : "include/llvm/Testing/Support/Error.h",
			"sourceGroupIndex" : 1
		},
		{
			"backtrace" : 3,
			"path" : "include/llvm/Testing/Support/SupportHelpers.h",
			"sourceGroupIndex" : 1
		}
	],
	"type" : "STATIC_LIBRARY"
}

=== ProphetofAtnu/CMakeFileAPISchema/tests/target-Bye-Debug-721bd84bddf4d4e84fbc.json
{
	"artifacts" : 
	[
		{
			"path" : "lib/Bye.dylib"
		}
	],
	"backtrace" : 4,
	"backtraceGraph" : 
	{
		"commands" : 
		[
			"add_library",
			"llvm_add_library",
			"add_llvm_library",
			"add_llvm_pass_plugin",
			"add_dependencies",
			"set_property",
			"llvm_update_compile_flags",
			"add_compile_definitions",
			"include",
			"include_directories"
		],
		"files" : 
		[
			"cmake/modules/AddLLVM.cmake",
			"examples/Bye/CMakeLists.txt",
			"cmake/modules/HandleLLVMOptions.cmake",
			"CMakeLists.txt"
		],
		"nodes" : 
		[
			{
				"file" : 1
			},
			{
				"command" : 3,
				"file" : 1,
				"line" : 10,
				"parent" : 0
			},
			{
				"command" : 2,
				"file" : 0,
				"line" : 1094,
				"parent" : 1
			},
			{
				"command" : 1,
				"file" : 0,
				"line" : 848,
				"parent" : 2
			},
			{
				"command" : 0,
				"file" : 0,
				"line" : 585,
				"parent" : 3
			},
			{
				"command" : 4,
				"file" : 0,
				"line" : 721,
				"parent" : 3
			},
			{
				"command" : 6,
				"file" : 0,
				"line" : 614,
				"parent" : 3
			},
			{
				"command" : 5,
				"file" : 0,
				"line" : 83,
				"parent" : 6
			},
			{
				"file" : 3
			},
			{
				"command" : 8,
				"file" : 3,
				"line" : 926,
				"parent" : 8
			},
			{
				"file" : 2,
				"parent" : 9
			},
			{
				"command" : 7,
				"file" : 2,
				"line" : 92,
				"parent" : 10
			},
			{
				"command" : 7,
				"file" : 2,
				"line" : 113,
				"parent" : 10
			},
			{
				"command" : 7,
				"file" : 2,
				"line" : 1053,
				"parent" : 10
			},
			{
				"command" : 7,
				"file" : 2,
				"line" : 1054,
				"parent" : 10
			},
			{
				"command" : 7,
				"file" : 2,
				"line" : 1055,
				"parent" : 10
			},
			{
				"command" : 9,
				"file" : 3,
				"line" : 1133,
				"parent" : 8
			}
		]
	},
	"compileGroups" : 
	[
		{
			"compileCommandFragments" : 
			[
				{
					"fragment" : " -fPIC -fvisibility-inlines-hidden -Werror=date-time -Werror=unguarded-availability-new -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -pedantic -Wno-long-long -Wc++98-compat-extra-semi -Wimplicit-fallthrough -Wcovered-switch-default -Wno-noexcept-type -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -Wsuggest-override -Wstring-conversion -Wmisleading-indentation -Wctad-maybe-unsupported -g -std=c++17 -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk -fPIC"
				},
				{
					"fragment" : " -fno-exceptions -funwind-tables -fno-rtti"
				}
			],
			"defines" : 
			[
				{
					"backtrace" : 7,
					"define" : "GTEST_HAS_RTTI=0"
				},
				{
					"backtrace" : 11,
					"define" : "_DEBUG"
				},
				{
					"backtrace" : 12,
					"define" : "_GLIBCXX_ASSERTIONS"
				},
				{
					"backtrace" : 13,
					"define" : "__STDC_CONSTANT_MACROS"
				},
				{
					"backtrace" : 14,
					"define" : "__STDC_FORMAT_MACROS"
				},
				{
					"backtrace" : 15,
					"define" : "__STDC_LIMIT_MACROS"
				}
			],
			"includes" : 
			[
				{
					"path" : "/Users/jacsc/Code/install/llvm-build/examples/Bye"
				},
				{
					"path" : "/Users/jacsc/Code/install/llvm-project/llvm/examples/Bye"
				},
				{
					"backtrace" : 16,
					"path" : "/Users/jacsc/Code/install/llvm-build/include"
				},
				{
					"backtrace" : 16,
					"path" : "/Users/jacsc/Code/install/llvm-project/llvm/include"
				}
			],
			"language" : "CXX",
			"languageStandard" : 
			{
				"backtraces" : 
				[
					4
				],
				"standard" : "17"
			},
			"sourceIndexes" : 
			[
				0
			]
		}
	],
	"dependencies" : 
	[
		{
			"backtrace" : 5,
			"id" : "intrinsics_gen::@6eda0283a7d1115d7bbd"
		}
	],
	"folder" : 
	{
		"name" : "Loadable modules"
	},
	"id" : "Bye::@959325562bb79a68c91a",
	"link" : 
	{
		"commandFragments" : 
		[
			{
				"fragment" : "-L/Users/jacsc/Code/install/ChezScheme/.build/lib -L/opt/homebrew/opt/llvm/lib -Wl,-flat_namespace -Wl,-undefined -Wl,suppress",
				"role" : "flags"
			},
			{
				"fragment" : "-Wl,-rpath,@loader_path/../lib",
				"role" : "libraries"
			}
		],
		"language" : "CXX"
	},
	"name" : "Bye",
	"nameOnDisk" : "Bye.dylib",
	"paths" : 
	{
		"build" : "examples/Bye",
		"source" : "examples/Bye"
	},
	"sourceGroups" : 
	[
		{
			"name" : "Source Files",
			"sourceIndexes" : 
			[
				0
			]
		}
	],
	"sources" : 
	[
		{
			"backtrace" : 4,
			"compileGroupIndex" : 0,
			"path" : "examples/Bye/Bye.cpp",
			"sourceGroupIndex" : 0
		}
	],
	"type" : "MODULE_LIBRARY"
}

=== ProphetofAtnu/CMakeFileAPISchema/tests/target-obj.LLVMTableGenCommon-Debug-470312b9beb0a14004a5.json
{
	"artifacts" : 
	[
		{
			"path" : "utils/TableGen/CMakeFiles/obj.LLVMTableGenCommon.dir/Attributes.cpp.o"
		},
		{
			"path" : "utils/TableGen/CMakeFiles/obj.LLVMTableGenCommon.dir/CodeGenIntrinsics.cpp.o"
		},
		{
			"path" : "utils/TableGen/CMakeFiles/obj.LLVMTableGenCommon.dir/DirectiveEmitter.cpp.o"
		},
		{
			"path" : "utils/TableGen/CMakeFiles/obj.LLVMTableGenCommon.dir/IntrinsicEmitter.cpp.o"
		},
		{
			"path" : "utils/TableGen/CMakeFiles/obj.LLVMTableGenCommon.dir/RISCVTargetDefEmitter.cpp.o"
		},
		{
			"path" : "utils/TableGen/CMakeFiles/obj.LLVMTableGenCommon.dir/SDNodeProperties.cpp.o"
		},
		{
			"path" : "utils/TableGen/CMakeFiles/obj.LLVMTableGenCommon.dir/VTEmitter.cpp.o"
		}
	],
	"backtrace" : 3,
	"backtraceGraph" : 
	{
		"commands" : 
		[
			"add_library",
			"llvm_add_library",
			"add_llvm_library",
			"set_property",
			"llvm_update_compile_flags",
			"add_compile_definitions",
			"include",
			"include_directories",
			"target_include_directories"
		],
		"files" : 
		[
			"cmake/modules/AddLLVM.cmake",
			"utils/TableGen/CMakeLists.txt",
			"cmake/modules/HandleLLVMOptions.cmake",
			"CMakeLists.txt"
		],
		"nodes" : 
		[
			{
				"file" : 1
			},
			{
				"command" : 2,
				"file" : 1,
				"line" : 3,
				"parent" : 0
			},
			{
				"command" : 1,
				"file" : 0,
				"line" : 852,
				"parent" : 1
			},
			{
				"command" : 0,
				"file" : 0,
				"line" : 519,
				"parent" : 2
			},
			{
				"command" : 4,
				"file" : 0,
				"line" : 522,
				"parent" : 2
			},
			{
				"command" : 3,
				"file" : 0,
				"line" : 83,
				"parent" : 4
			},
			{
				"file" : 3
			},
			{
				"command" : 6,
				"file" : 3,
				"line" : 926,
				"parent" : 6
			},
			{
				"file" : 2,
				"parent" : 7
			},
			{
				"command" : 5,
				"file" : 2,
				"line" : 92,
				"parent" : 8
			},
			{
				"command" : 5,
				"file" : 2,
				"line" : 113,
				"parent" : 8
			},
			{
				"command" : 5,
				"file" : 2,
				"line" : 1053,
				"parent" : 8
			},
			{
				"command" : 5,
				"file" : 2,
				"line" : 1054,
				"parent" : 8
			},
			{
				"command" : 5,
				"file" : 2,
				"line" : 1055,
				"parent" : 8
			},
			{
				"command" : 7,
				"file" : 3,
				"line" : 1133,
				"parent" : 6
			},
			{
				"command" : 8,
				"file" : 0,
				"line" : 534,
				"parent" : 2
			}
		]
	},
	"compileGroups" : 
	[
		{
			"compileCommandFragments" : 
			[
				{
					"fragment" : " -fPIC -fvisibility-inlines-hidden -Werror=date-time -Werror=unguarded-availability-new -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -pedantic -Wno-long-long -Wc++98-compat-extra-semi -Wimplicit-fallthrough -Wcovered-switch-default -Wno-noexcept-type -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -Wsuggest-override -Wstring-conversion -Wmisleading-indentation -Wctad-maybe-unsupported -g -std=c++17 -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk"
				},
				{
					"fragment" : " -fno-exceptions -funwind-tables -fno-rtti"
				}
			],
			"defines" : 
			[
				{
					"backtrace" : 5,
					"define" : "GTEST_HAS_RTTI=0"
				},
				{
					"backtrace" : 9,
					"define" : "_DEBUG"
				},
				{
					"backtrace" : 10,
					"define" : "_GLIBCXX_ASSERTIONS"
				},
				{
					"backtrace" : 11,
					"define" : "__STDC_CONSTANT_MACROS"
				},
				{
					"backtrace" : 12,
					"define" : "__STDC_FORMAT_MACROS"
				},
				{
					"backtrace" : 13,
					"define" : "__STDC_LIMIT_MACROS"
				}
			],
			"includes" : 
			[
				{
					"path" : "/Users/jacsc/Code/install/llvm-build/utils/TableGen"
				},
				{
					"path" : "/Users/jacsc/Code/install/llvm-project/llvm/utils/TableGen"
				},
				{
					"backtrace" : 14,
					"path" : "/Users/jacsc/Code/install/llvm-build/include"
				},
				{
					"backtrace" : 14,
					"path" : "/Users/jacsc/Code/install/llvm-project/llvm/include"
				},
				{
					"backtrace" : 15,
					"path" : "/opt/homebrew/include"
				}
			],
			"language" : "CXX",
			"languageStandard" : 
			{
				"backtraces" : 
				[
					3
				],
				"standard" : "17"
			},
			"sourceIndexes" : 
			[
				0,
				1,
				2,
				3,
				4,
				5,
				6
			]
		}
	],
	"folder" : 
	{
		"name" : "Object Libraries"
	},
	"id" : "obj.LLVMTableGenCommon::@dca47d54282c16282dfc",
	"name" : "obj.LLVMTableGenCommon",
	"paths" : 
	{
		"build" : "utils/TableGen",
		"source" : "utils/TableGen"
	},
	"sourceGroups" : 
	[
		{
			"name" : "Source Files",
			"sourceIndexes" : 
			[
				0,
				1,
				2,
				3,
				4,
				5,
				6
			]
		},
		{
			"name" : "Header Files",
			"sourceIndexes" : 
			[
				7,
				8,
				9,
				10,
				11,
				12,
				13,
				14,
				15,
				16,
				17,
				18,
				19,
				20,
				21,
				22,
				23,
				24,
				25,
				26,
				27,
				28,
				29,
				30,
				31,
				32,
				33
			]
		}
	],
	"sources" : 
	[
		{
			"backtrace" : 3,
			"compileGroupIndex" : 0,
			"path" : "utils/TableGen/Attributes.cpp",
			"sourceGroupIndex" : 0
		},
		{
			"backtrace" : 3,
			"compileGroupIndex" : 0,
			"path" : "utils/TableGen/CodeGenIntrinsics.cpp",
			"sourceGroupIndex" : 0
		},
		{
			"backtrace" : 3,
			"compileGroupIndex" : 0,
			"path" : "utils/TableGen/DirectiveEmitter.cpp",
			"sourceGroupIndex" : 0
		},
		{
			"backtrace" : 3,
			"compileGroupIndex" : 0,
			"path" : "utils/TableGen/IntrinsicEmitter.cpp",
			"sourceGroupIndex" : 0
		},
		{
			"backtrace" : 3,
			"compileGroupIndex" : 0,
			"path" : "utils/TableGen/RISCVTargetDefEmitter.cpp",
			"sourceGroupIndex" : 0
		},
		{
			"backtrace" : 3,
			"compileGroupIndex" : 0,
			"path" : "utils/TableGen/SDNodeProperties.cpp",
			"sourceGroupIndex" : 0
		},
		{
			"backtrace" : 3,
			"compileGroupIndex" : 0,
			"path" : "utils/TableGen/VTEmitter.cpp",
			"sourceGroupIndex" : 0
		},
		{
			"backtrace" : 3,
			"path" : "utils/TableGen/AsmWriterInst.h",
			"sourceGroupIndex" : 1
		},
		{
			"backtrace" : 3,
			"path" : "utils/TableGen/CodeGenDAGPatterns.h",
			"sourceGroupIndex" : 1
		},
		{
			"backtrace" : 3,
			"path" : "utils/TableGen/CodeGenHwModes.h",
			"sourceGroupIndex" : 1
		},
		{
			"backtrace" : 3,
			"path" : "utils/TableGen/CodeGenInstAlias.h",
			"sourceGroupIndex" : 1
		},
		{
			"backtrace" : 3,
			"path" : "utils/TableGen/CodeGenInstruction.h",
			"sourceGroupIndex" : 1
		},
		{
			"backtrace" : 3,
			"path" : "utils/TableGen/CodeGenIntrinsics.h",
			"sourceGroupIndex" : 1
		},
		{
			"backtrace" : 3,
			"path" : "utils/TableGen/CodeGenRegisters.h",
			"sourceGroupIndex" : 1
		},
		{
			"backtrace" : 3,
			"path" : "utils/TableGen/CodeGenSchedule.h",
			"sourceGroupIndex" : 1
		},
		{
			"backtrace" : 3,
			"path" : "utils/TableGen/CodeGenTarget.h",
			"sourceGroupIndex" : 1
		},
		{
			"backtrace" : 3,
			"path" : "utils/TableGen/DAGISelMatcher.h",
			"sourceGroupIndex" : 1
		},
		{
			"backtrace" : 3,
			"path" : "utils/TableGen/DFAEmitter.h",
			"sourceGroupIndex" : 1
		},
		{
			"backtrace" : 3,
			"path" : "utils/TableGen/GlobalISelMatchTable.h",
			"sourceGroupIndex" : 1
		},
		{
			"backtrace" : 3,
			"path" : "utils/TableGen/GlobalISelMatchTableExecutorEmitter.h",
			"sourceGroupIndex" : 1
		},
		{
			"backtrace" : 3,
			"path" : "utils/TableGen/InfoByHwMode.h",
			"sourceGroupIndex" : 1
		},
		{
			"backtrace" : 3,
			"path" : "utils/TableGen/OptEmitter.h",
			"sourceGroupIndex" : 1
		},
		{
			"backtrace" : 3,
			"path" : "utils/TableGen/PredicateExpander.h",
			"sourceGroupIndex" : 1
		},
		{
			"backtrace" : 3,
			"path" : "utils/TableGen/SDNodeProperties.h",
			"sourceGroupIndex" : 1
		},
		{
			"backtrace" : 3,
			"path" : "utils/TableGen/SequenceToOffsetTable.h",
			"sourceGroupIndex" : 1
		},
		{
			"backtrace" : 3,
			"path" : "utils/TableGen/SubtargetFeatureInfo.h",
			"sourceGroupIndex" : 1
		},
		{
			"backtrace" : 3,
			"path" : "utils/TableGen/TableGenBackends.h",
			"sourceGroupIndex" : 1
		},
		{
			"backtrace" : 3,
			"path" : "utils/TableGen/Types.h",
			"sourceGroupIndex" : 1
		},
		{
			"backtrace" : 3,
			"path" : "utils/TableGen/VarLenCodeEmitterGen.h",
			"sourceGroupIndex" : 1
		},
		{
			"backtrace" : 3,
			"path" : "utils/TableGen/WebAssemblyDisassemblerEmitter.h",
			"sourceGroupIndex" : 1
		},
		{
			"backtrace" : 3,
			"path" : "utils/TableGen/X86DisassemblerShared.h",
			"sourceGroupIndex" : 1
		},
		{
			"backtrace" : 3,
			"path" : "utils/TableGen/X86DisassemblerTables.h",
			"sourceGroupIndex" : 1
		},
		{
			"backtrace" : 3,
			"path" : "utils/TableGen/X86ModRMFilters.h",
			"sourceGroupIndex" : 1
		},
		{
			"backtrace" : 3,
			"path" : "utils/TableGen/X86RecognizableInstr.h",
			"sourceGroupIndex" : 1
		}
	],
	"type" : "OBJECT_LIBRARY"
}
