=== ProphetofAtnu/CMakeFileAPISchema/schema/codemodel-v2-target.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "title": "CodeModel v2 Target File",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "name",
    "id",
    "type",
    "backtrace",
    "paths",
    "sources"
  ],
  "properties": {
    "name": {
      "type": "string"
    },
    "id": {
      "type": "string"
    },
    "type": {
      "type": "string",
      "enum": [
        "EXECUTABLE",
        "STATIC_LIBRARY",
        "SHARED_LIBRARY",
        "MODULE_LIBRARY",
        "OBJECT_LIBRARY",
        "INTERFACE_LIBRARY",
        "UTILITY"
      ]
    },
    "backtrace": {
      "type": "integer"
    },
    "folder": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "name"
      ],
      "properties": {
        "name": {
          "type": "string"
        }
      }
    },
    "paths": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "source",
        "build"
      ],
      "properties": {
        "source": {
          "type": "string"
        },
        "build": {
          "type": "string"
        }
      }
    },
    "nameOnDisk": {
      "type": "string"
    },
    "artifacts": {
      "type": "array",
      "items": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "path"
        ],
        "properties": {
          "path": {
            "type": "string"
          }
        }
      }
    },
    "isGeneratorProvided": {
      "type": "boolean"
    },
    "install": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "prefix",
        "destinations"
      ],
      "properties": {
        "prefix": {
          "type": "object",
          "additionalProperties": false,
          "required": [
            "path"
          ],
          "properties": {
            "path": {
              "type": "string"
            }
          }
        },
        "destinations": {
          "type": "array",
          "items": {
            "type": "object",
            "additionalProperties": false,
            "required": [
              "path"
            ],
            "properties": {
              "path": {
                "type": "string"
              },
              "backtrace": {
                "type": "integer"
              }
            }
          }
        }
      }
    },
    "link": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "language"
      ],
      "properties": {
        "language": {
          "type": "string"
        },
        "commandFragments": {
          "type": "array",
          "items": {
            "type": "object",
            "additionalProperties": false,
            "required": [
              "fragment",
              "role"
            ],
            "properties": {
              "fragment": {
                "type": "string"
              },
              "role": {
                "type": "string",
                "enum": [
                  "flags",
                  "libraries",
                  "libraryPath",
                  "frameworkPath"
                ]
              },
              "backtrace": {
                "type": "integer"
              }
            }
          }
        },
        "lto": {
          "type": "boolean"
        },
        "sysroot": {
          "type": "object",
          "required": [
            "path"
          ],
          "properties": {
            "path": {
              "type": "string"
            }
          }
        }
      }
    },
    "archive": {
      "type": "object",
      "properties": {
        "commandFragments": {
          "type": "object",
          "required": [
            "fragment",
            "role"
          ],
          "properties": {
            "fragment": {
              "type": "string"
            },
            "role": {
              "type": "string",
              "enum": [
                "flags",
                "libraries",
                "libraryPath",
                "frameworkPath"
              ]
            }
          }
        },
        "lto": {
          "type": "boolean"
        }
      }
    },
    "dependencies": {
      "type": "array",
      "items": {
        "$id": "dependency",
        "type": "object",
        "required": [
          "id"
        ],
        "properties": {
          "id": {
            "type": "string"
          },
          "backtrace": {
            "type": "integer"
          }
        }
      }
    },
    "fileSets": {
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "name",
          "type",
          "visibility",
          "baseDirectories"
        ],
        "properties": {
          "name": {
            "type": "string"
          },
          "type": {
            "type": "string"
          },
          "visibility": {
            "type": "string",
            "enum": [
              "PUBLIC",
              "PRIVATE",
              "INTERFACE"
            ]
          },
          "baseDirectories": {
            "type": "array",
            "items": {
              "type": "string"
            }
          }
        }
      }
    },
    "sources": {
      "type": "array",
      "items": {
        "$id": "source",
        "type": "object",
        "required": [
          "path"
        ],
        "properties": {
          "path": {
            "type": "string"
          },
          "compileGroupIndex": {
            "type": "integer"
          },
          "sourceGroupIndex": {
            "type": "integer"
          },
          "isGenerated": {
            "type": "boolean"
          },
          "fileSetIndex": {
            "type": "integer"
          },
          "backtrace": {
            "type": "integer"
          }
        }
      }
    },
    "sourceGroups": {
      "type": "array",
      "items": {
        "$id": "sourceGroup",
        "type": "object",
        "required": [
          "name",
          "sourceIndexes"
        ],
        "properties": {
          "name": {
            "type": "string"
          },
          "sourceIndexes": {
            "type": "array",
            "items": {
              "type": "integer"
            }
          }
        }
      }
    },
    "compileGroups": {
      "type": "array",
      "items": {
        "$id": "sourceGroup",
        "type": "object",
        "required": [
          "sourceIndexes",
          "language"
        ],
        "properties": {
          "sourceIndexes": {
            "type": "array",
            "items": {
              "type": "integer"
            }
          },
          "language": {
            "type": "string"
          },
          "languageStandard": {
            "type": "object",
            "required": [
              "standard"
            ],
            "properties": {
              "backtraces": {
                "type": "array",
                "items": {
                  "type": "integer"
                }
              },
              "standard": {
                "type": "string"
              }
            }
          },
          "compileCommandFragments": {
            "type": "array",
            "items": {
              "type": "object",
              "required": [
                "fragment"
              ],
              "properties": {
                "fragment": {
                  "type": "string"
                }
              }
            }
          },
          "includes": {
            "type": "array",
            "items": {
              "type": "object",
              "required": [
                "path"
              ],
              "properties": {
                "path": {
                  "type": "string"
                },
                "isSystem": {
                  "type": "boolean"
                },
                "backtrace": {
                  "type": "integer"
                }
              }
            }
          },
          "frameworks": {
            "type": "array",
            "items": {
              "type": "object",
              "required": [
                "items"
              ],
              "properties": {
                "path": {
                  "type": "string"
                },
                "isSystem": {
                  "type": "boolean"
                },
                "backtrace": {
                  "type": "integer"
                }
              }
            }
          },
          "precompileHeaders": {
            "type": "array",
            "items": {
              "type": "object",
              "required": [
                "header"
              ],
              "properties": {
                "header": {
                  "type": "string"
                },
                "backtrace": {
                  "type": "integer"
                }
              }
            }
          },
          "defines": {
            "type": "array",
            "items": {
              "$id": "define",
              "type": "object",
              "required": [
                "define"
              ],
              "properties": {
                "define": {
                  "type": "string"
                },
                "backtrace": {
                  "type": "integer"
                }
              }
            }
          },
          "sysroot": {
            "type": "object",
            "required": [
              "path"
            ],
            "properties": {
              "path": {
                "type": "string"
              }
            }
          }
        }
      }
    },
    "backtraceGraph": {
      "$ref": "./codemodel-v2-backtrace-graph.json"
    }
  }
}

=== ProphetofAtnu/CMakeFileAPISchema/tests/target-Remarks-Debug-4e19993cc812e67d48dc.json
{
	"artifacts" : 
	[
		{
			"path" : "lib/libRemarks.dylib"
		}
	],
	"backtrace" : 3,
	"backtraceGraph" : 
	{
		"commands" : 
		[
			"add_library",
			"llvm_add_library",
			"add_llvm_library",
			"install",
			"target_link_libraries",
			"LLVMBuildResolveComponentsLink",
			"add_llvm_component_library",
			"add_dependencies",
			"add_llvm_symbol_exports",
			"set_property",
			"llvm_update_compile_flags",
			"add_compile_definitions",
			"include",
			"include_directories"
		],
		"files" : 
		[
			"cmake/modules/AddLLVM.cmake",
			"tools/remarks-shlib/CMakeLists.txt",
			"cmake/modules/LLVM-Build.cmake",
			"lib/CMakeLists.txt",
			"lib/Support/CMakeLists.txt",
			"cmake/modules/HandleLLVMOptions.cmake",
			"CMakeLists.txt"
		],
		"nodes" : 
		[
			{
				"file" : 1
			},
			{
				"command" : 2,
				"file" : 1,
				"line" : 16,
				"parent" : 0
			},
			{
				"command" : 1,
				"file" : 0,
				"line" : 850,
				"parent" : 1
			},
			{
				"command" : 0,
				"file" : 0,
				"line" : 588,
				"parent" : 2
			},
			{
				"command" : 3,
				"file" : 0,
				"line" : 879,
				"parent" : 1
			},
			{
				"command" : 4,
				"file" : 0,
				"line" : 714,
				"parent" : 2
			},
			{
				"file" : 3
			},
			{
				"command" : 5,
				"file" : 3,
				"line" : 67,
				"parent" : 6
			},
			{
				"command" : 4,
				"file" : 2,
				"line" : 101,
				"parent" : 7
			},
			{
				"file" : 4
			},
			{
				"command" : 6,
				"file" : 4,
				"line" : 132,
				"parent" : 9
			},
			{
				"command" : 2,
				"file" : 0,
				"line" : 827,
				"parent" : 10
			},
			{
				"command" : 1,
				"file" : 0,
				"line" : 852,
				"parent" : 11
			},
			{
				"command" : 4,
				"file" : 0,
				"line" : 714,
				"parent" : 12
			},
			{
				"command" : 4,
				"file" : 2,
				"line" : 101,
				"parent" : 7
			},
			{
				"command" : 8,
				"file" : 0,
				"line" : 657,
				"parent" : 2
			},
			{
				"command" : 7,
				"file" : 0,
				"line" : 178,
				"parent" : 15
			},
			{
				"command" : 10,
				"file" : 0,
				"line" : 614,
				"parent" : 2
			},
			{
				"command" : 9,
				"file" : 0,
				"line" : 83,
				"parent" : 17
			},
			{
				"file" : 6
			},
			{
				"command" : 12,
				"file" : 6,
				"line" : 926,
				"parent" : 19
			},
			{
				"file" : 5,
				"parent" : 20
			},
			{
				"command" : 11,
				"file" : 5,
				"line" : 92,
				"parent" : 21
			},
			{
				"command" : 11,
				"file" : 5,
				"line" : 113,
				"parent" : 21
			},
			{
				"command" : 11,
				"file" : 5,
				"line" : 1053,
				"parent" : 21
			},
			{
				"command" : 11,
				"file" : 5,
				"line" : 1054,
				"parent" : 21
			},
			{
				"command" : 11,
				"file" : 5,
				"line" : 1055,
				"parent" : 21
			},
			{
				"command" : 13,
				"file" : 6,
				"line" : 1133,
				"parent" : 19
			}
		]
	},
	"compileGroups" : 
	[
		{
			"compileCommandFragments" : 
			[
				{
					"fragment" : " -fPIC -fvisibility-inlines-hidden -Werror=date-time -Werror=unguarded-availability-new -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -pedantic -Wno-long-long -Wc++98-compat-extra-semi -Wimplicit-fallthrough -Wcovered-switch-default -Wno-noexcept-type -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -Wsuggest-override -Wstring-conversion -Wmisleading-indentation -Wctad-maybe-unsupported -g -std=c++17 -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk -fPIC"
				},
				{
					"fragment" : " -fno-exceptions -funwind-tables -fno-rtti"
				}
			],
			"defines" : 
			[
				{
					"backtrace" : 18,
					"define" : "GTEST_HAS_RTTI=0"
				},
				{
					"backtrace" : 22,
					"define" : "_DEBUG"
				},
				{
					"backtrace" : 23,
					"define" : "_GLIBCXX_ASSERTIONS"
				},
				{
					"backtrace" : 24,
					"define" : "__STDC_CONSTANT_MACROS"
				},
				{
					"backtrace" : 25,
					"define" : "__STDC_FORMAT_MACROS"
				},
				{
					"backtrace" : 26,
					"define" : "__STDC_LIMIT_MACROS"
				}
			],
			"includes" : 
			[
				{
					"path" : "/Users/jacsc/Code/install/llvm-build/tools/remarks-shlib"
				},
				{
					"path" : "/Users/jacsc/Code/install/llvm-project/llvm/tools/remarks-shlib"
				},
				{
					"backtrace" : 27,
					"path" : "/Users/jacsc/Code/install/llvm-build/include"
				},
				{
					"backtrace" : 27,
					"path" : "/Users/jacsc/Code/install/llvm-project/llvm/include"
				},
				{
					"backtrace" : 5,
					"isSystem" : true,
					"path" : "/opt/homebrew/include"
				}
			],
			"language" : "CXX",
			"languageStandard" : 
			{
				"backtraces" : 
				[
					3
				],
				"standard" : "17"
			},
			"sourceIndexes" : 
			[
				0
			]
		}
	],
	"dependencies" : 
	[
		{
			"backtrace" : 5,
			"id" : "LLVMDemangle::@3c7ef39cff93a35ba752"
		},
		{
			"backtrace" : 5,
			"id" : "LLVMSupport::@928d1708d80fe1f55e59"
		},
		{
			"backtrace" : 5,
			"id" : "LLVMBitstreamReader::@95731b79b16df93229d4"
		},
		{
			"backtrace" : 5,
			"id" : "LLVMRemarks::@6a63c042d04b6deafc56"
		},
		{
			"backtrace" : 16,
			"id" : "Remarks_exports::@f7dec6e8b9f0a1fc96de"
		}
	],
	"folder" : 
	{
		"name" : "Libraries"
	},
	"id" : "Remarks::@f7dec6e8b9f0a1fc96de",
	"install" : 
	{
		"destinations" : 
		[
			{
				"backtrace" : 4,
				"path" : "lib"
			},
			{
				"backtrace" : 4,
				"path" : "lib"
			}
		],
		"prefix" : 
		{
			"path" : "/usr/local"
		}
	},
	"link" : 
	{
		"commandFragments" : 
		[
			{
				"fragment" : "-L/Users/jacsc/Code/install/ChezScheme/.build/lib -L/opt/homebrew/opt/llvm/lib   -Wl,-exported_symbols_list,\"/Users/jacsc/Code/install/llvm-build/tools/remarks-shlib/Remarks.exports\" -compatibility_version 1 -current_version 18.0.0",
				"role" : "flags"
			},
			{
				"fragment" : "-Wl,-rpath,@loader_path/../lib",
				"role" : "libraries"
			},
			{
				"backtrace" : 5,
				"fragment" : "../../lib/libLLVMRemarks.a",
				"role" : "libraries"
			},
			{
				"backtrace" : 8,
				"fragment" : "../../lib/libLLVMBitstreamReader.a",
				"role" : "libraries"
			},
			{
				"backtrace" : 8,
				"fragment" : "../../lib/libLLVMSupport.a",
				"role" : "libraries"
			},
			{
				"backtrace" : 13,
				"fragment" : "-lm",
				"role" : "libraries"
			},
			{
				"backtrace" : 13,
				"fragment" : "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk/usr/lib/libz.tbd",
				"role" : "libraries"
			},
			{
				"backtrace" : 13,
				"fragment" : "/opt/homebrew/lib/libzstd.dylib",
				"role" : "libraries"
			},
			{
				"backtrace" : 13,
				"fragment" : "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk/usr/lib/libcurses.tbd",
				"role" : "libraries"
			},
			{
				"backtrace" : 14,
				"fragment" : "../../lib/libLLVMDemangle.a",
				"role" : "libraries"
			}
		],
		"language" : "CXX"
	},
	"name" : "Remarks",
	"nameOnDisk" : "libRemarks.dylib",
	"paths" : 
	{
		"build" : "tools/remarks-shlib",
		"source" : "tools/remarks-shlib"
	},
	"sourceGroups" : 
	[
		{
			"name" : "Source Files",
			"sourceIndexes" : 
			[
				0
			]
		}
	],
	"sources" : 
	[
		{
			"backtrace" : 3,
			"compileGroupIndex" : 0,
			"path" : "tools/remarks-shlib/libremarks.cpp",
			"sourceGroupIndex" : 0
		}
	],
	"type" : "SHARED_LIBRARY"
}

=== ProphetofAtnu/CMakeFileAPISchema/tests/target-LLVMHello-Debug-bd5e2d2df18171a90068.json
{
	"artifacts" : 
	[
		{
			"path" : "lib/LLVMHello.dylib"
		}
	],
	"backtrace" : 3,
	"backtraceGraph" : 
	{
		"commands" : 
		[
			"add_library",
			"llvm_add_library",
			"add_llvm_library",
			"add_dependencies",
			"add_llvm_symbol_exports",
			"set_property",
			"llvm_update_compile_flags",
			"add_compile_definitions",
			"include",
			"include_directories"
		],
		"files" : 
		[
			"cmake/modules/AddLLVM.cmake",
			"lib/Transforms/Hello/CMakeLists.txt",
			"cmake/modules/HandleLLVMOptions.cmake",
			"CMakeLists.txt"
		],
		"nodes" : 
		[
			{
				"file" : 1
			},
			{
				"command" : 2,
				"file" : 1,
				"line" : 13,
				"parent" : 0
			},
			{
				"command" : 1,
				"file" : 0,
				"line" : 848,
				"parent" : 1
			},
			{
				"command" : 0,
				"file" : 0,
				"line" : 585,
				"parent" : 2
			},
			{
				"command" : 3,
				"file" : 0,
				"line" : 721,
				"parent" : 2
			},
			{
				"command" : 4,
				"file" : 0,
				"line" : 657,
				"parent" : 2
			},
			{
				"command" : 3,
				"file" : 0,
				"line" : 178,
				"parent" : 5
			},
			{
				"command" : 6,
				"file" : 0,
				"line" : 614,
				"parent" : 2
			},
			{
				"command" : 5,
				"file" : 0,
				"line" : 83,
				"parent" : 7
			},
			{
				"file" : 3
			},
			{
				"command" : 8,
				"file" : 3,
				"line" : 926,
				"parent" : 9
			},
			{
				"file" : 2,
				"parent" : 10
			},
			{
				"command" : 7,
				"file" : 2,
				"line" : 92,
				"parent" : 11
			},
			{
				"command" : 7,
				"file" : 2,
				"line" : 113,
				"parent" : 11
			},
			{
				"command" : 7,
				"file" : 2,
				"line" : 1053,
				"parent" : 11
			},
			{
				"command" : 7,
				"file" : 2,
				"line" : 1054,
				"parent" : 11
			},
			{
				"command" : 7,
				"file" : 2,
				"line" : 1055,
				"parent" : 11
			},
			{
				"command" : 9,
				"file" : 3,
				"line" : 1133,
				"parent" : 9
			}
		]
	},
	"compileGroups" : 
	[
		{
			"compileCommandFragments" : 
			[
				{
					"fragment" : " -fPIC -fvisibility-inlines-hidden -Werror=date-time -Werror=unguarded-availability-new -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -pedantic -Wno-long-long -Wc++98-compat-extra-semi -Wimplicit-fallthrough -Wcovered-switch-default -Wno-noexcept-type -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -Wsuggest-override -Wstring-conversion -Wmisleading-indentation -Wctad-maybe-unsupported -g -std=c++17 -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk -fPIC"
				},
				{
					"fragment" : " -fno-exceptions -funwind-tables -fno-rtti"
				}
			],
			"defines" : 
			[
				{
					"backtrace" : 8,
					"define" : "GTEST_HAS_RTTI=0"
				},
				{
					"backtrace" : 12,
					"define" : "_DEBUG"
				},
				{
					"backtrace" : 13,
					"define" : "_GLIBCXX_ASSERTIONS"
				},
				{
					"backtrace" : 14,
					"define" : "__STDC_CONSTANT_MACROS"
				},
				{
					"backtrace" : 15,
					"define" : "__STDC_FORMAT_MACROS"
				},
				{
					"backtrace" : 16,
					"define" : "__STDC_LIMIT_MACROS"
				}
			],
			"includes" : 
			[
				{
					"path" : "/Users/jacsc/Code/install/llvm-build/lib/Transforms/Hello"
				},
				{
					"path" : "/Users/jacsc/Code/install/llvm-project/llvm/lib/Transforms/Hello"
				},
				{
					"backtrace" : 17,
					"path" : "/Users/jacsc/Code/install/llvm-build/include"
				},
				{
					"backtrace" : 17,
					"path" : "/Users/jacsc/Code/install/llvm-project/llvm/include"
				}
			],
			"language" : "CXX",
			"languageStandard" : 
			{
				"backtraces" : 
				[
					3
				],
				"standard" : "17"
			},
			"sourceIndexes" : 
			[
				0
			]
		}
	],
	"dependencies" : 
	[
		{
			"backtrace" : 4,
			"id" : "intrinsics_gen::@6eda0283a7d1115d7bbd"
		},
		{
			"backtrace" : 6,
			"id" : "LLVMHello_exports::@48ed1eff02c32f32e24c"
		}
	],
	"folder" : 
	{
		"name" : "Loadable modules"
	},
	"id" : "LLVMHello::@48ed1eff02c32f32e24c",
	"link" : 
	{
		"commandFragments" : 
		[
			{
				"fragment" : "-L/Users/jacsc/Code/install/ChezScheme/.build/lib -L/opt/homebrew/opt/llvm/lib -Wl,-flat_namespace -Wl,-undefined -Wl,suppress   -Wl,-exported_symbols_list,\"/Users/jacsc/Code/install/llvm-build/lib/Transforms/Hello/LLVMHello.exports\"",
				"role" : "flags"
			},
			{
				"fragment" : "-Wl,-rpath,@loader_path/../lib",
				"role" : "libraries"
			}
		],
		"language" : "CXX"
	},
	"name" : "LLVMHello",
	"nameOnDisk" : "LLVMHello.dylib",
	"paths" : 
	{
		"build" : "lib/Transforms/Hello",
		"source" : "lib/Transforms/Hello"
	},
	"sourceGroups" : 
	[
		{
			"name" : "Source Files",
			"sourceIndexes" : 
			[
				0
			]
		}
	],
	"sources" : 
	[
		{
			"backtrace" : 3,
			"compileGroupIndex" : 0,
			"path" : "lib/Transforms/Hello/Hello.cpp",
			"sourceGroupIndex" : 0
		}
	],
	"type" : "MODULE_LIBRARY"
}

=== ProphetofAtnu/CMakeFileAPISchema/tests/target-LLVMWindowsDriver-Debug-79b58505f1c976167999.json
{
	"archive" : {},
	"artifacts" : 
	[
		{
			"path" : "lib/libLLVMWindowsDriver.a"
		}
	],
	"backtrace" : 4,
	"backtraceGraph" : 
	{
		"commands" : 
		[
			"add_library",
			"llvm_add_library",
			"add_llvm_library",
			"add_llvm_component_library",
			"install",
			"target_link_libraries",
			"LLVMBuildResolveComponentsLink",
			"set_property",
			"llvm_update_compile_flags",
			"add_compile_definitions",
			"include",
			"include_directories"
		],
		"files" : 
		[
			"cmake/modules/AddLLVM.cmake",
			"lib/WindowsDriver/CMakeLists.txt",
			"cmake/modules/LLVM-Build.cmake",
			"lib/CMakeLists.txt",
			"cmake/modules/HandleLLVMOptions.cmake",
			"CMakeLists.txt"
		],
		"nodes" : 
		[
			{
				"file" : 1
			},
			{
				"command" : 3,
				"file" : 1,
				"line" : 1,
				"parent" : 0
			},
			{
				"command" : 2,
				"file" : 0,
				"line" : 827,
				"parent" : 1
			},
			{
				"command" : 1,
				"file" : 0,
				"line" : 852,
				"parent" : 2
			},
			{
				"command" : 0,
				"file" : 0,
				"line" : 590,
				"parent" : 3
			},
			{
				"command" : 4,
				"file" : 0,
				"line" : 879,
				"parent" : 2
			},
			{
				"file" : 3
			},
			{
				"command" : 6,
				"file" : 3,
				"line" : 67,
				"parent" : 6
			},
			{
				"command" : 5,
				"file" : 2,
				"line" : 101,
				"parent" : 7
			},
			{
				"command" : 8,
				"file" : 0,
				"line" : 614,
				"parent" : 3
			},
			{
				"command" : 7,
				"file" : 0,
				"line" : 83,
				"parent" : 9
			},
			{
				"file" : 5
			},
			{
				"command" : 10,
				"file" : 5,
				"line" : 926,
				"parent" : 11
			},
			{
				"file" : 4,
				"parent" : 12
			},
			{
				"command" : 9,
				"file" : 4,
				"line" : 92,
				"parent" : 13
			},
			{
				"command" : 9,
				"file" : 4,
				"line" : 113,
				"parent" : 13
			},
			{
				"command" : 9,
				"file" : 4,
				"line" : 1053,
				"parent" : 13
			},
			{
				"command" : 9,
				"file" : 4,
				"line" : 1054,
				"parent" : 13
			},
			{
				"command" : 9,
				"file" : 4,
				"line" : 1055,
				"parent" : 13
			},
			{
				"command" : 11,
				"file" : 5,
				"line" : 1133,
				"parent" : 11
			}
		]
	},
	"compileGroups" : 
	[
		{
			"compileCommandFragments" : 
			[
				{
					"fragment" : " -fPIC -fvisibility-inlines-hidden -Werror=date-time -Werror=unguarded-availability-new -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -pedantic -Wno-long-long -Wc++98-compat-extra-semi -Wimplicit-fallthrough -Wcovered-switch-default -Wno-noexcept-type -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -Wsuggest-override -Wstring-conversion -Wmisleading-indentation -Wctad-maybe-unsupported -g -std=c++17 -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk"
				},
				{
					"fragment" : " -fno-exceptions -funwind-tables -fno-rtti"
				}
			],
			"defines" : 
			[
				{
					"backtrace" : 10,
					"define" : "GTEST_HAS_RTTI=0"
				},
				{
					"backtrace" : 14,
					"define" : "_DEBUG"
				},
				{
					"backtrace" : 15,
					"define" : "_GLIBCXX_ASSERTIONS"
				},
				{
					"backtrace" : 16,
					"define" : "__STDC_CONSTANT_MACROS"
				},
				{
					"backtrace" : 17,
					"define" : "__STDC_FORMAT_MACROS"
				},
				{
					"backtrace" : 18,
					"define" : "__STDC_LIMIT_MACROS"
				}
			],
			"includes" : 
			[
				{
					"path" : "/Users/jacsc/Code/install/llvm-build/lib/WindowsDriver"
				},
				{
					"path" : "/Users/jacsc/Code/install/llvm-project/llvm/lib/WindowsDriver"
				},
				{
					"backtrace" : 19,
					"path" : "/Users/jacsc/Code/install/llvm-build/include"
				},
				{
					"backtrace" : 19,
					"path" : "/Users/jacsc/Code/install/llvm-project/llvm/include"
				},
				{
					"backtrace" : 8,
					"isSystem" : true,
					"path" : "/opt/homebrew/include"
				}
			],
			"language" : "CXX",
			"languageStandard" : 
			{
				"backtraces" : 
				[
					4
				],
				"standard" : "17"
			},
			"sourceIndexes" : 
			[
				0
			]
		}
	],
	"dependencies" : 
	[
		{
			"backtrace" : 8,
			"id" : "LLVMDemangle::@3c7ef39cff93a35ba752"
		},
		{
			"backtrace" : 8,
			"id" : "LLVMSupport::@928d1708d80fe1f55e59"
		},
		{
			"backtrace" : 8,
			"id" : "LLVMOption::@03597dd37d3dc3b95065"
		},
		{
			"backtrace" : 8,
			"id" : "LLVMTargetParser::@49fd776d486540152370"
		}
	],
	"folder" : 
	{
		"name" : "Libraries"
	},
	"id" : "LLVMWindowsDriver::@67e0b031e165bff462f4",
	"install" : 
	{
		"destinations" : 
		[
			{
				"backtrace" : 5,
				"path" : "lib"
			}
		],
		"prefix" : 
		{
			"path" : "/usr/local"
		}
	},
	"name" : "LLVMWindowsDriver",
	"nameOnDisk" : "libLLVMWindowsDriver.a",
	"paths" : 
	{
		"build" : "lib/WindowsDriver",
		"source" : "lib/WindowsDriver"
	},
	"sourceGroups" : 
	[
		{
			"name" : "Source Files",
			"sourceIndexes" : 
			[
				0
			]
		},
		{
			"name" : "Header Files",
			"sourceIndexes" : 
			[
				1,
				2
			]
		}
	],
	"sources" : 
	[
		{
			"backtrace" : 4,
			"compileGroupIndex" : 0,
			"path" : "lib/WindowsDriver/MSVCPaths.cpp",
			"sourceGroupIndex" : 0
		},
		{
			"backtrace" : 4,
			"path" : "include/llvm/WindowsDriver/MSVCPaths.h",
			"sourceGroupIndex" : 1
		},
		{
			"backtrace" : 4,
			"path" : "include/llvm/WindowsDriver/MSVCSetupApi.h",
			"sourceGroupIndex" : 1
		}
	],
	"type" : "STATIC_LIBRARY"
}
