=== ProphetofAtnu/CMakeFileAPISchema/schema/codemodel-v2-target.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "title": "CodeModel v2 Target File",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "name",
    "id",
    "type",
    "backtrace",
    "paths",
    "sources"
  ],
  "properties": {
    "name": {
      "type": "string"
    },
    "id": {
      "type": "string"
    },
    "type": {
      "type": "string",
      "enum": [
        "EXECUTABLE",
        "STATIC_LIBRARY",
        "SHARED_LIBRARY",
        "MODULE_LIBRARY",
        "OBJECT_LIBRARY",
        "INTERFACE_LIBRARY",
        "UTILITY"
      ]
    },
    "backtrace": {
      "type": "integer"
    },
    "folder": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "name"
      ],
      "properties": {
        "name": {
          "type": "string"
        }
      }
    },
    "paths": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "source",
        "build"
      ],
      "properties": {
        "source": {
          "type": "string"
        },
        "build": {
          "type": "string"
        }
      }
    },
    "nameOnDisk": {
      "type": "string"
    },
    "artifacts": {
      "type": "array",
      "items": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "path"
        ],
        "properties": {
          "path": {
            "type": "string"
          }
        }
      }
    },
    "isGeneratorProvided": {
      "type": "boolean"
    },
    "install": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "prefix",
        "destinations"
      ],
      "properties": {
        "prefix": {
          "type": "object",
          "additionalProperties": false,
          "required": [
            "path"
          ],
          "properties": {
            "path": {
              "type": "string"
            }
          }
        },
        "destinations": {
          "type": "array",
          "items": {
            "type": "object",
            "additionalProperties": false,
            "required": [
              "path"
            ],
            "properties": {
              "path": {
                "type": "string"
              },
              "backtrace": {
                "type": "integer"
              }
            }
          }
        }
      }
    },
    "link": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "language"
      ],
      "properties": {
        "language": {
          "type": "string"
        },
        "commandFragments": {
          "type": "array",
          "items": {
            "type": "object",
            "additionalProperties": false,
            "required": [
              "fragment",
              "role"
            ],
            "properties": {
              "fragment": {
                "type": "string"
              },
              "role": {
                "type": "string",
                "enum": [
                  "flags",
                  "libraries",
                  "libraryPath",
                  "frameworkPath"
                ]
              },
              "backtrace": {
                "type": "integer"
              }
            }
          }
        },
        "lto": {
          "type": "boolean"
        },
        "sysroot": {
          "type": "object",
          "required": [
            "path"
          ],
          "properties": {
            "path": {
              "type": "string"
            }
          }
        }
      }
    },
    "archive": {
      "type": "object",
      "properties": {
        "commandFragments": {
          "type": "object",
          "required": [
            "fragment",
            "role"
          ],
          "properties": {
            "fragment": {
              "type": "string"
            },
            "role": {
              "type": "string",
              "enum": [
                "flags",
                "libraries",
                "libraryPath",
                "frameworkPath"
              ]
            }
          }
        },
        "lto": {
          "type": "boolean"
        }
      }
    },
    "dependencies": {
      "type": "array",
      "items": {
        "$id": "dependency",
        "type": "object",
        "required": [
          "id"
        ],
        "properties": {
          "id": {
            "type": "string"
          },
          "backtrace": {
            "type": "integer"
          }
        }
      }
    },
    "fileSets": {
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "name",
          "type",
          "visibility",
          "baseDirectories"
        ],
        "properties": {
          "name": {
            "type": "string"
          },
          "type": {
            "type": "string"
          },
          "visibility": {
            "type": "string",
            "enum": [
              "PUBLIC",
              "PRIVATE",
              "INTERFACE"
            ]
          },
          "baseDirectories": {
            "type": "array",
            "items": {
              "type": "string"
            }
          }
        }
      }
    },
    "sources": {
      "type": "array",
      "items": {
        "$id": "source",
        "type": "object",
        "required": [
          "path"
        ],
        "properties": {
          "path": {
            "type": "string"
          },
          "compileGroupIndex": {
            "type": "integer"
          },
          "sourceGroupIndex": {
            "type": "integer"
          },
          "isGenerated": {
            "type": "boolean"
          },
          "fileSetIndex": {
            "type": "integer"
          },
          "backtrace": {
            "type": "integer"
          }
        }
      }
    },
    "sourceGroups": {
      "type": "array",
      "items": {
        "$id": "sourceGroup",
        "type": "object",
        "required": [
          "name",
          "sourceIndexes"
        ],
        "properties": {
          "name": {
            "type": "string"
          },
          "sourceIndexes": {
            "type": "array",
            "items": {
              "type": "integer"
            }
          }
        }
      }
    },
    "compileGroups": {
      "type": "array",
      "items": {
        "$id": "sourceGroup",
        "type": "object",
        "required": [
          "sourceIndexes",
          "language"
        ],
        "properties": {
          "sourceIndexes": {
            "type": "array",
            "items": {
              "type": "integer"
            }
          },
          "language": {
            "type": "string"
          },
          "languageStandard": {
            "type": "object",
            "required": [
              "standard"
            ],
            "properties": {
              "backtraces": {
                "type": "array",
                "items": {
                  "type": "integer"
                }
              },
              "standard": {
                "type": "string"
              }
            }
          },
          "compileCommandFragments": {
            "type": "array",
            "items": {
              "type": "object",
              "required": [
                "fragment"
              ],
              "properties": {
                "fragment": {
                  "type": "string"
                }
              }
            }
          },
          "includes": {
            "type": "array",
            "items": {
              "type": "object",
              "required": [
                "path"
              ],
              "properties": {
                "path": {
                  "type": "string"
                },
                "isSystem": {
                  "type": "boolean"
                },
                "backtrace": {
                  "type": "integer"
                }
              }
            }
          },
          "frameworks": {
            "type": "array",
            "items": {
              "type": "object",
              "required": [
                "items"
              ],
              "properties": {
                "path": {
                  "type": "string"
                },
                "isSystem": {
                  "type": "boolean"
                },
                "backtrace": {
                  "type": "integer"
                }
              }
            }
          },
          "precompileHeaders": {
            "type": "array",
            "items": {
              "type": "object",
              "required": [
                "header"
              ],
              "properties": {
                "header": {
                  "type": "string"
                },
                "backtrace": {
                  "type": "integer"
                }
              }
            }
          },
          "defines": {
            "type": "array",
            "items": {
              "$id": "define",
              "type": "object",
              "required": [
                "define"
              ],
              "properties": {
                "define": {
                  "type": "string"
                },
                "backtrace": {
                  "type": "integer"
                }
              }
            }
          },
          "sysroot": {
            "type": "object",
            "required": [
              "path"
            ],
            "properties": {
              "path": {
                "type": "string"
              }
            }
          }
        }
      }
    },
    "backtraceGraph": {
      "$ref": "./codemodel-v2-backtrace-graph.json"
    }
  }
}

=== ProphetofAtnu/CMakeFileAPISchema/tests/target-llvm-yaml-parser-fuzzer-Debug-5264f3039f11d7ceb2f5.json
{
	"artifacts" : 
	[
		{
			"path" : "bin/llvm-yaml-parser-fuzzer"
		}
	],
	"backtrace" : 3,
	"backtraceGraph" : 
	{
		"commands" : 
		[
			"add_executable",
			"add_llvm_executable",
			"add_llvm_fuzzer",
			"target_link_libraries",
			"explicit_llvm_config",
			"llvm_config",
			"LLVMBuildResolveComponentsLink",
			"llvm_add_library",
			"add_llvm_library",
			"add_llvm_component_library",
			"set_property",
			"llvm_update_compile_flags",
			"add_compile_definitions",
			"include",
			"include_directories"
		],
		"files" : 
		[
			"cmake/modules/AddLLVM.cmake",
			"tools/llvm-yaml-parser-fuzzer/CMakeLists.txt",
			"cmake/modules/LLVM-Config.cmake",
			"cmake/modules/LLVM-Build.cmake",
			"lib/CMakeLists.txt",
			"lib/Support/CMakeLists.txt",
			"cmake/modules/HandleLLVMOptions.cmake",
			"CMakeLists.txt"
		],
		"nodes" : 
		[
			{
				"file" : 1
			},
			{
				"command" : 2,
				"file" : 1,
				"line" : 6,
				"parent" : 0
			},
			{
				"command" : 1,
				"file" : 0,
				"line" : 1450,
				"parent" : 1
			},
			{
				"command" : 0,
				"file" : 0,
				"line" : 969,
				"parent" : 2
			},
			{
				"command" : 5,
				"file" : 0,
				"line" : 1016,
				"parent" : 2
			},
			{
				"command" : 4,
				"file" : 2,
				"line" : 98,
				"parent" : 4
			},
			{
				"command" : 3,
				"file" : 2,
				"line" : 110,
				"parent" : 5
			},
			{
				"file" : 4
			},
			{
				"command" : 6,
				"file" : 4,
				"line" : 67,
				"parent" : 7
			},
			{
				"command" : 3,
				"file" : 3,
				"line" : 101,
				"parent" : 8
			},
			{
				"file" : 5
			},
			{
				"command" : 9,
				"file" : 5,
				"line" : 132,
				"parent" : 10
			},
			{
				"command" : 8,
				"file" : 0,
				"line" : 827,
				"parent" : 11
			},
			{
				"command" : 7,
				"file" : 0,
				"line" : 852,
				"parent" : 12
			},
			{
				"command" : 3,
				"file" : 0,
				"line" : 714,
				"parent" : 13
			},
			{
				"command" : 3,
				"file" : 3,
				"line" : 101,
				"parent" : 8
			},
			{
				"command" : 11,
				"file" : 0,
				"line" : 991,
				"parent" : 2
			},
			{
				"command" : 10,
				"file" : 0,
				"line" : 83,
				"parent" : 16
			},
			{
				"file" : 7
			},
			{
				"command" : 13,
				"file" : 7,
				"line" : 926,
				"parent" : 18
			},
			{
				"file" : 6,
				"parent" : 19
			},
			{
				"command" : 12,
				"file" : 6,
				"line" : 92,
				"parent" : 20
			},
			{
				"command" : 12,
				"file" : 6,
				"line" : 113,
				"parent" : 20
			},
			{
				"command" : 12,
				"file" : 6,
				"line" : 1053,
				"parent" : 20
			},
			{
				"command" : 12,
				"file" : 6,
				"line" : 1054,
				"parent" : 20
			},
			{
				"command" : 12,
				"file" : 6,
				"line" : 1055,
				"parent" : 20
			},
			{
				"command" : 14,
				"file" : 7,
				"line" : 1133,
				"parent" : 18
			}
		]
	},
	"compileGroups" : 
	[
		{
			"compileCommandFragments" : 
			[
				{
					"fragment" : " -fPIC -fvisibility-inlines-hidden -Werror=date-time -Werror=unguarded-availability-new -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -pedantic -Wno-long-long -Wc++98-compat-extra-semi -Wimplicit-fallthrough -Wcovered-switch-default -Wno-noexcept-type -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -Wsuggest-override -Wstring-conversion -Wmisleading-indentation -Wctad-maybe-unsupported -g -std=c++17 -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk"
				},
				{
					"fragment" : " -fno-exceptions -funwind-tables -fno-rtti"
				}
			],
			"defines" : 
			[
				{
					"backtrace" : 17,
					"define" : "GTEST_HAS_RTTI=0"
				},
				{
					"backtrace" : 21,
					"define" : "_DEBUG"
				},
				{
					"backtrace" : 22,
					"define" : "_GLIBCXX_ASSERTIONS"
				},
				{
					"backtrace" : 23,
					"define" : "__STDC_CONSTANT_MACROS"
				},
				{
					"backtrace" : 24,
					"define" : "__STDC_FORMAT_MACROS"
				},
				{
					"backtrace" : 25,
					"define" : "__STDC_LIMIT_MACROS"
				}
			],
			"includes" : 
			[
				{
					"path" : "/Users/jacsc/Code/install/llvm-build/tools/llvm-yaml-parser-fuzzer"
				},
				{
					"path" : "/Users/jacsc/Code/install/llvm-project/llvm/tools/llvm-yaml-parser-fuzzer"
				},
				{
					"backtrace" : 26,
					"path" : "/Users/jacsc/Code/install/llvm-build/include"
				},
				{
					"backtrace" : 26,
					"path" : "/Users/jacsc/Code/install/llvm-project/llvm/include"
				},
				{
					"backtrace" : 6,
					"isSystem" : true,
					"path" : "/opt/homebrew/include"
				}
			],
			"language" : "CXX",
			"languageStandard" : 
			{
				"backtraces" : 
				[
					3
				],
				"standard" : "17"
			},
			"sourceIndexes" : 
			[
				0,
				1
			]
		}
	],
	"dependencies" : 
	[
		{
			"backtrace" : 6,
			"id" : "LLVMDemangle::@3c7ef39cff93a35ba752"
		},
		{
			"backtrace" : 6,
			"id" : "LLVMSupport::@928d1708d80fe1f55e59"
		},
		{
			"backtrace" : 6,
			"id" : "LLVMFuzzerCLI::@5c563885927a2b6284fa"
		},
		{
			"backtrace" : 6,
			"id" : "LLVMTargetParser::@49fd776d486540152370"
		}
	],
	"folder" : 
	{
		"name" : "Fuzzers"
	},
	"id" : "llvm-yaml-parser-fuzzer::@fe27f8bab4b97f3d17ff",
	"link" : 
	{
		"commandFragments" : 
		[
			{
				"fragment" : "-fPIC -fvisibility-inlines-hidden -Werror=date-time -Werror=unguarded-availability-new -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -pedantic -Wno-long-long -Wc++98-compat-extra-semi -Wimplicit-fallthrough -Wcovered-switch-default -Wno-noexcept-type -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -Wsuggest-override -Wstring-conversion -Wmisleading-indentation -Wctad-maybe-unsupported -g",
				"role" : "flags"
			},
			{
				"fragment" : "-L/Users/jacsc/Code/install/ChezScheme/.build/lib -L/opt/homebrew/opt/llvm/lib",
				"role" : "flags"
			},
			{
				"fragment" : "-Wl,-rpath,@loader_path/../lib",
				"role" : "libraries"
			},
			{
				"backtrace" : 6,
				"fragment" : "../../lib/libLLVMSupport.a",
				"role" : "libraries"
			},
			{
				"backtrace" : 6,
				"fragment" : "../../lib/libLLVMFuzzerCLI.a",
				"role" : "libraries"
			},
			{
				"backtrace" : 9,
				"fragment" : "../../lib/libLLVMTargetParser.a",
				"role" : "libraries"
			},
			{
				"backtrace" : 6,
				"fragment" : "../../lib/libLLVMSupport.a",
				"role" : "libraries"
			},
			{
				"backtrace" : 14,
				"fragment" : "-lm",
				"role" : "libraries"
			},
			{
				"backtrace" : 14,
				"fragment" : "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk/usr/lib/libz.tbd",
				"role" : "libraries"
			},
			{
				"backtrace" : 14,
				"fragment" : "/opt/homebrew/lib/libzstd.dylib",
				"role" : "libraries"
			},
			{
				"backtrace" : 14,
				"fragment" : "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk/usr/lib/libcurses.tbd",
				"role" : "libraries"
			},
			{
				"backtrace" : 15,
				"fragment" : "../../lib/libLLVMDemangle.a",
				"role" : "libraries"
			}
		],
		"language" : "CXX"
	},
	"name" : "llvm-yaml-parser-fuzzer",
	"nameOnDisk" : "llvm-yaml-parser-fuzzer",
	"paths" : 
	{
		"build" : "tools/llvm-yaml-parser-fuzzer",
		"source" : "tools/llvm-yaml-parser-fuzzer"
	},
	"sourceGroups" : 
	[
		{
			"name" : "Source Files",
			"sourceIndexes" : 
			[
				0,
				1
			]
		}
	],
	"sources" : 
	[
		{
			"backtrace" : 3,
			"compileGroupIndex" : 0,
			"path" : "tools/llvm-yaml-parser-fuzzer/DummyYAMLParserFuzzer.cpp",
			"sourceGroupIndex" : 0
		},
		{
			"backtrace" : 3,
			"compileGroupIndex" : 0,
			"path" : "tools/llvm-yaml-parser-fuzzer/yaml-parser-fuzzer.cpp",
			"sourceGroupIndex" : 0
		}
	],
	"type" : "EXECUTABLE"
}

=== ProphetofAtnu/CMakeFileAPISchema/tests/target-benchmark_main-Debug-52038aef691092ded808.json
{
	"archive" : {},
	"artifacts" : 
	[
		{
			"path" : "lib/libbenchmark_main.a"
		}
	],
	"backtrace" : 1,
	"backtraceGraph" : 
	{
		"commands" : 
		[
			"add_library",
			"target_link_libraries",
			"add_definitions",
			"cxx_feature_check",
			"add_compile_definitions",
			"include",
			"include_directories"
		],
		"files" : 
		[
			"/Users/jacsc/Code/install/llvm-project/third-party/benchmark/src/CMakeLists.txt",
			"/Users/jacsc/Code/install/llvm-project/third-party/benchmark/cmake/CXXFeatureCheck.cmake",
			"/Users/jacsc/Code/install/llvm-project/third-party/benchmark/CMakeLists.txt",
			"cmake/modules/HandleLLVMOptions.cmake",
			"CMakeLists.txt"
		],
		"nodes" : 
		[
			{
				"file" : 0
			},
			{
				"command" : 0,
				"file" : 0,
				"line" : 57,
				"parent" : 0
			},
			{
				"command" : 1,
				"file" : 0,
				"line" : 64,
				"parent" : 0
			},
			{
				"file" : 2
			},
			{
				"command" : 3,
				"file" : 2,
				"line" : 302,
				"parent" : 3
			},
			{
				"command" : 2,
				"file" : 1,
				"line" : 61,
				"parent" : 4
			},
			{
				"command" : 3,
				"file" : 2,
				"line" : 300,
				"parent" : 3
			},
			{
				"command" : 2,
				"file" : 1,
				"line" : 26,
				"parent" : 6
			},
			{
				"command" : 3,
				"file" : 2,
				"line" : 311,
				"parent" : 3
			},
			{
				"command" : 2,
				"file" : 1,
				"line" : 61,
				"parent" : 8
			},
			{
				"file" : 4
			},
			{
				"command" : 5,
				"file" : 4,
				"line" : 926,
				"parent" : 10
			},
			{
				"file" : 3,
				"parent" : 11
			},
			{
				"command" : 4,
				"file" : 3,
				"line" : 92,
				"parent" : 12
			},
			{
				"command" : 4,
				"file" : 3,
				"line" : 113,
				"parent" : 12
			},
			{
				"command" : 4,
				"file" : 3,
				"line" : 1053,
				"parent" : 12
			},
			{
				"command" : 4,
				"file" : 3,
				"line" : 1054,
				"parent" : 12
			},
			{
				"command" : 4,
				"file" : 3,
				"line" : 1055,
				"parent" : 12
			},
			{
				"command" : 6,
				"file" : 4,
				"line" : 1133,
				"parent" : 10
			},
			{
				"command" : 6,
				"file" : 2,
				"line" : 321,
				"parent" : 3
			}
		]
	},
	"compileGroups" : 
	[
		{
			"compileCommandFragments" : 
			[
				{
					"fragment" : " -fPIC -fvisibility-inlines-hidden -Werror=date-time -Werror=unguarded-availability-new -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -pedantic -Wno-long-long -Wc++98-compat-extra-semi -Wimplicit-fallthrough -Wcovered-switch-default -Wno-noexcept-type -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -Wsuggest-override -Wstring-conversion -Wmisleading-indentation -Wctad-maybe-unsupported  -std=c++11  -Wall  -Wextra  -Wshadow  -Wsuggest-override  -pedantic  -pedantic-errors  -Wshorten-64-to-32  -fstrict-aliasing  -Wno-deprecated-declarations  -fno-exceptions  -Wstrict-aliasing  -Wthread-safety -g -std=c++17 -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk"
				}
			],
			"defines" : 
			[
				{
					"backtrace" : 5,
					"define" : "HAVE_POSIX_REGEX"
				},
				{
					"backtrace" : 7,
					"define" : "HAVE_STD_REGEX"
				},
				{
					"backtrace" : 9,
					"define" : "HAVE_STEADY_CLOCK"
				},
				{
					"backtrace" : 13,
					"define" : "_DEBUG"
				},
				{
					"backtrace" : 14,
					"define" : "_GLIBCXX_ASSERTIONS"
				},
				{
					"backtrace" : 15,
					"define" : "__STDC_CONSTANT_MACROS"
				},
				{
					"backtrace" : 16,
					"define" : "__STDC_FORMAT_MACROS"
				},
				{
					"backtrace" : 17,
					"define" : "__STDC_LIMIT_MACROS"
				}
			],
			"includes" : 
			[
				{
					"path" : "/Users/jacsc/Code/install/llvm-build/third-party/benchmark/src"
				},
				{
					"path" : "/Users/jacsc/Code/install/llvm-project/third-party/benchmark/src"
				},
				{
					"backtrace" : 18,
					"path" : "/Users/jacsc/Code/install/llvm-build/include"
				},
				{
					"backtrace" : 18,
					"path" : "/Users/jacsc/Code/install/llvm-project/llvm/include"
				},
				{
					"backtrace" : 19,
					"path" : "/Users/jacsc/Code/install/llvm-project/third-party/benchmark/include"
				}
			],
			"language" : "CXX",
			"languageStandard" : 
			{
				"backtraces" : 
				[
					1
				],
				"standard" : "17"
			},
			"sourceIndexes" : 
			[
				0
			]
		}
	],
	"dependencies" : 
	[
		{
			"backtrace" : 2,
			"id" : "benchmark::@d4f64cf0f57ed78b9a8d"
		}
	],
	"id" : "benchmark_main::@d4f64cf0f57ed78b9a8d",
	"name" : "benchmark_main",
	"nameOnDisk" : "libbenchmark_main.a",
	"paths" : 
	{
		"build" : "third-party/benchmark/src",
		"source" : "/Users/jacsc/Code/install/llvm-project/third-party/benchmark/src"
	},
	"sourceGroups" : 
	[
		{
			"name" : "Source Files",
			"sourceIndexes" : 
			[
				0
			]
		}
	],
	"sources" : 
	[
		{
			"backtrace" : 1,
			"compileGroupIndex" : 0,
			"path" : "/Users/jacsc/Code/install/llvm-project/third-party/benchmark/src/benchmark_main.cc",
			"sourceGroupIndex" : 0
		}
	],
	"type" : "STATIC_LIBRARY"
}

=== ProphetofAtnu/CMakeFileAPISchema/tests/target-llvm_gtest_main-Debug-5920b822b3bf733f60c8.json
{
	"archive" : {},
	"artifacts" : 
	[
		{
			"path" : "lib/libllvm_gtest_main.a"
		}
	],
	"backtrace" : 3,
	"backtraceGraph" : 
	{
		"commands" : 
		[
			"add_library",
			"llvm_add_library",
			"add_llvm_library",
			"target_link_libraries",
			"add_definitions",
			"add_compile_definitions",
			"include",
			"include_directories"
		],
		"files" : 
		[
			"cmake/modules/AddLLVM.cmake",
			"/Users/jacsc/Code/install/llvm-project/third-party/unittest/UnitTestMain/CMakeLists.txt",
			"/Users/jacsc/Code/install/llvm-project/third-party/unittest/CMakeLists.txt",
			"cmake/modules/HandleLLVMOptions.cmake",
			"CMakeLists.txt"
		],
		"nodes" : 
		[
			{
				"file" : 1
			},
			{
				"command" : 2,
				"file" : 1,
				"line" : 6,
				"parent" : 0
			},
			{
				"command" : 1,
				"file" : 0,
				"line" : 852,
				"parent" : 1
			},
			{
				"command" : 0,
				"file" : 0,
				"line" : 590,
				"parent" : 2
			},
			{
				"command" : 3,
				"file" : 0,
				"line" : 714,
				"parent" : 2
			},
			{
				"file" : 2
			},
			{
				"command" : 4,
				"file" : 2,
				"line" : 35,
				"parent" : 5
			},
			{
				"file" : 4
			},
			{
				"command" : 6,
				"file" : 4,
				"line" : 926,
				"parent" : 7
			},
			{
				"file" : 3,
				"parent" : 8
			},
			{
				"command" : 5,
				"file" : 3,
				"line" : 92,
				"parent" : 9
			},
			{
				"command" : 5,
				"file" : 3,
				"line" : 113,
				"parent" : 9
			},
			{
				"command" : 5,
				"file" : 3,
				"line" : 1053,
				"parent" : 9
			},
			{
				"command" : 5,
				"file" : 3,
				"line" : 1054,
				"parent" : 9
			},
			{
				"command" : 5,
				"file" : 3,
				"line" : 1055,
				"parent" : 9
			},
			{
				"command" : 7,
				"file" : 4,
				"line" : 1133,
				"parent" : 7
			}
		]
	},
	"compileGroups" : 
	[
		{
			"compileCommandFragments" : 
			[
				{
					"fragment" : " -fPIC -fvisibility-inlines-hidden -Werror=date-time -Werror=unguarded-availability-new -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -pedantic -Wno-long-long -Wc++98-compat-extra-semi -Wimplicit-fallthrough -Wcovered-switch-default -Wno-noexcept-type -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -Wsuggest-override -Wstring-conversion -Wmisleading-indentation -Wctad-maybe-unsupported -g -std=c++17 -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk   -Wno-variadic-macros -Wno-gnu-zero-variadic-macro-arguments -Wno-covered-switch-default -Wno-suggest-override"
				},
				{
					"fragment" : " -fno-exceptions -funwind-tables"
				},
				{
					"backtrace" : 4,
					"fragment" : "-Wno-suggest-override"
				}
			],
			"defines" : 
			[
				{
					"backtrace" : 6,
					"define" : "GTEST_HAS_RTTI=0"
				},
				{
					"backtrace" : 10,
					"define" : "_DEBUG"
				},
				{
					"backtrace" : 11,
					"define" : "_GLIBCXX_ASSERTIONS"
				},
				{
					"backtrace" : 12,
					"define" : "__STDC_CONSTANT_MACROS"
				},
				{
					"backtrace" : 13,
					"define" : "__STDC_FORMAT_MACROS"
				},
				{
					"backtrace" : 14,
					"define" : "__STDC_LIMIT_MACROS"
				}
			],
			"includes" : 
			[
				{
					"path" : "/Users/jacsc/Code/install/llvm-build/third-party/unittest/UnitTestMain"
				},
				{
					"path" : "/Users/jacsc/Code/install/llvm-project/third-party/unittest/UnitTestMain"
				},
				{
					"backtrace" : 15,
					"path" : "/Users/jacsc/Code/install/llvm-build/include"
				},
				{
					"backtrace" : 15,
					"path" : "/Users/jacsc/Code/install/llvm-project/llvm/include"
				},
				{
					"backtrace" : 4,
					"path" : "/Users/jacsc/Code/install/llvm-project/third-party/unittest/googletest/include"
				},
				{
					"backtrace" : 4,
					"path" : "/Users/jacsc/Code/install/llvm-project/third-party/unittest/googlemock/include"
				},
				{
					"backtrace" : 4,
					"isSystem" : true,
					"path" : "/opt/homebrew/include"
				}
			],
			"language" : "CXX",
			"languageStandard" : 
			{
				"backtraces" : 
				[
					3
				],
				"standard" : "17"
			},
			"sourceIndexes" : 
			[
				0
			]
		}
	],
	"dependencies" : 
	[
		{
			"backtrace" : 4,
			"id" : "LLVMDemangle::@3c7ef39cff93a35ba752"
		},
		{
			"backtrace" : 4,
			"id" : "LLVMSupport::@928d1708d80fe1f55e59"
		},
		{
			"backtrace" : 4,
			"id" : "llvm_gtest::@0f58997ba806a3fe2530"
		}
	],
	"folder" : 
	{
		"name" : "Libraries"
	},
	"id" : "llvm_gtest_main::@6aed8c35274cf854cb51",
	"name" : "llvm_gtest_main",
	"nameOnDisk" : "libllvm_gtest_main.a",
	"paths" : 
	{
		"build" : "third-party/unittest/UnitTestMain",
		"source" : "/Users/jacsc/Code/install/llvm-project/third-party/unittest/UnitTestMain"
	},
	"sourceGroups" : 
	[
		{
			"name" : "Source Files",
			"sourceIndexes" : 
			[
				0
			]
		}
	],
	"sources" : 
	[
		{
			"backtrace" : 3,
			"compileGroupIndex" : 0,
			"path" : "/Users/jacsc/Code/install/llvm-project/third-party/unittest/UnitTestMain/TestMain.cpp",
			"sourceGroupIndex" : 0
		}
	],
	"type" : "STATIC_LIBRARY"
}
